# Generated by Django 3.2.16 on 2023-01-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_profile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stripe_requirements_true',
            field=models.BooleanField(default=True),
        ),
    ]
