# Generated by Django 3.2.16 on 2023-01-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_stripe_requirements_true'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='stripe_requirements_true',
            new_name='stripe_requirements_due',
        ),
    ]
