# Generated by Django 3.2.16 on 2023-01-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20230126_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_phone_number',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
