# Generated by Django 3.2.16 on 2023-01-26 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_userprofile_default_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be numbers only. Up to 15 digits allowed.', regex='^\\d{6,15}$')]),
        ),
    ]
