# Generated by Django 3.2.16 on 2023-01-26 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_userprofile_default_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_phone_number',
            field=models.CharField(blank=True, default='0', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be numbers only. Up to 20 digits allowed.', regex='^\\w[0-9]{6,15}$')]),
        ),
    ]
