# Generated by Django 3.2.16 on 2022-12-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpenseLineItem',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='rating',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='price',
            new_name='net_amount',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='has_sizes',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='title',
        ),
        migrations.AddField(
            model_name='expense',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='supplier_name',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='total_tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
