# Generated by Django 3.2.16 on 2023-01-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20230107_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='order_number',
            field=models.CharField(editable=False, max_length=32),
        ),
    ]
