# Generated by Django 3.2.16 on 2023-01-08 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_stripe_customer_id'),
        ('expenses', '0004_alter_expense_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='order_number',
            new_name='expense_id',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='lineitem_total',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='tip_amount',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='profiles.userprofile'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='expenses.expense')),
            ],
        ),
    ]
