# Generated by Django 3.2.16 on 2023-01-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_expense_net_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='image',
            field=models.ImageField(default='image', null=True, upload_to='media/user_upload_files/'),
        ),
    ]
