# Generated by Django 3.2.16 on 2023-01-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_auto_20230108_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
