# Generated by Django 3.2.16 on 2023-01-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_orderlineitem_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
