# Generated by Django 3.2.16 on 2023-01-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_expense_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
