# Generated by Django 3.2.16 on 2023-01-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_auto_20230110_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='stripe_pid',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
    ]
