# Generated by Django 3.2.16 on 2023-01-10 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0011_auto_20230110_2015'),
        ('profiles', '0002_alter_userprofile_stripe_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=254, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='expenses.expense')),
                ('user_recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_receiver', to='profiles.userprofile')),
                ('user_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_sender', to='profiles.userprofile')),
            ],
        ),
    ]
