# Generated by Django 3.2.16 on 2023-01-15 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_profile_image_url'),
        ('expenses', '0012_alter_orderlineitem_stripe_pid'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout_transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=254, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('stripe_pid', models.CharField(default='', max_length=254)),
                ('line_items', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_items', to='expenses.orderlineitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='expenses.expense')),
                ('user_recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_receiver', to='profiles.userprofile')),
                ('user_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_sender', to='profiles.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='transaction',
        ),
    ]
